language: c
sudo: required
dist: trusty
services:
  - docker
env:
  - TR_ARCH=local       GCOV=1
  - TR_ARCH=local       CLANG=1
  - TR_ARCH=x86_64
  - TR_ARCH=armv7hf
  - TR_ARCH=aarch64
  - TR_ARCH=ppc64le
  - TR_ARCH=alpine
script:
  - sudo make -C scripts/travis $TR_ARCH
after_success:
  - make -C scripts/travis after_success
